### ISSUE TITLE
Feature request - package for MacOS

### ISSUE THREAD

**Issue by bugok** [jaymzh/sugarjar#102]
From the readme file: 

> Currently we provide packages for Fedora, CentOS, Debian, and Ubuntu, but if you want others, file an Issue. 

Can we please have a MacOS release? Maybe using brew? 

@eliganim will appreciate this :)

**Comment by jaymzh** [comment]
I'd love to see a brew package. I'd prefer to have a packager for that though, someone who uses and is familiar with Brew.

However, Omnibus supports `.pkg`/`.dmg` packages, and I'll try to do that next time I do a release.

**Comment by jaymzh** [comment]
OK, there's a Mac `pkg` package up for the new 0.0.11 release!

**Comment by bugok** [comment]
Thanks @jaymzh!
